### ISSUE TITLE
0 bytes psgs_w100_embedding_bge-large-en-v1.5.pkl

### ISSUE THREAD

**Issue by HH446** [BeastyZ/LLM-Verified-Retrieval#2]
Hi! What a great work!

But I have some problems with reproduction.

When I run `bash commands/asqa_iterative_retrieval.sh`, it successfullyembedding. BUT KILLED with the following print.

...
Inference Embeddings: 100%|█████████▉| 82091/82092 [9:42:45<00:00,  2.03it/s]
Inference Embeddings: 100%|██████████| 82092/82092 [9:42:45<00:00,  2.35it/s]
commands/asqa_iterative_retrieval.sh: line 50: 979910 Killed                  python Iterative_retrieval.py --max_iteration $max_iteration --dataset_name $dataset_name --use_sub_questions $use_sub_questions --use_title $use_title --used_doc_field $used_doc_field --openai_model_name $openai_model_name --input_file $input_file --retriever $retriever --update_prompt_file $update_prompt_file --update_query_using_missing_info_from_question_and_psgs $update_query_using_missing_info_from_question_and_psgs --corpus_path $corpus_path --prompt_style $prompt_style --target_used_field $target_used_field --max_tokens $max_tokens --position $position --reranking_prompt_file $reranking_prompt_file --doc_num $doc_num --window_size $window_size --demo_file $demo_file --filtration_prompt_file $filtration_prompt_file --filtration_method $filtration_method
*****************************
start run.py
*****************************
...

THEN, I WILL GET 0 bytes psgs_w100_embedding_bge-large-en-v1.5.pkl in ./embedding.

**Comment by BeastyZ** [comment]
Hi, welcome to reproduce our work!

Sorry to hear about the failure of reproduction. I believe it is closely related to your hardware, which means that the memory required for embedding exceeds the upper limit specified by the operating system. That's why your process will be killed and the embeddings cannot be saved properly.
Given your situation, I suggest using a device with larger running memory or manually dividing the corpus into several parts, encoding them separately, and then merging these embeddings.

**Comment by HH446** [comment]
OH!
Thanks for your response！

That is the bad news,  because I don't have a better machine.

Would you mind sharing the corresponding .pkl file?

**Comment by BeastyZ** [comment]
I think it's a bit difficult because the complete embedding has 44GB. But I will try my best to upload it to the cloud drive.

**Comment by HH446** [comment]
Thanks!

**Comment by HH446** [comment]
Would you mind sharing the experiment configuration you have used? About the running memory and GPU?

**Comment by BeastyZ** [comment]
We completed our experiment on a high-performance server.

**[CPU info]**
processor       : 127
vendor_id       : GenuineIntel
cpu family      : 6
model           : 106
model name      : Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz
stepping        : 6
microcode       : 0xd000389
cpu MHz         : 3200.000
cache size      : 49152 KB

**[Running Memory info]**
|               | Total   | Used  | Free  | Shared | Buff/Cache | Available |
|---------------|---------|-------|-------|--------|------------|-----------|
| **Mem:**      | 1.0Ti   | 62Gi  | 794Gi | 3.0Mi  | 150Gi      | 939Gi     |
| **Swap:**     | 8.0Gi   | 4.5Gi | 3.5Gi |        |            |           |

**[GPU info]**
NVIDIA A800 * 80GB * 8

**Comment by BeastyZ** [comment]
> OH! Thanks for your response！
> 
> That is the bad news, because I don't have a better machine.
> 
> Would you mind sharing the corresponding .pkl file?

I'm afraid I cannot share the embedding with you because of the frequent Internet connection errors. I am unable to download the embedding directly from the server because the file size is too large, resulting in frequent connection errors. Without the embedding being done on my local computer, I cannot upload it to the cloud drive.

I suggest manually dividing the corpus into several parts, encoding them separately, and then merging these embeddings.
